name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-setuptools \
            python3-venv \
            libffi-dev \
            libssl-dev \
            liblzma-dev \
            zlib1g-dev \
            libjpeg-dev \
            libfreetype6-dev \
            cmake

      - name: Install buildozer and sdkmanager deps
        run: |
          pip install --upgrade pip
          pip install buildozer Cython

          # sdkmanager needs these tools
          sudo apt install -y wget tar

          # create Android SDK dir path the same way buildozer will
          mkdir -p $HOME/.buildozer/android/platform

          # Download commandline-tools (SDK manager)
          cd $HOME/.buildozer/android/platform
          mkdir -p android-sdk/cmdline-tools
          cd android-sdk/cmdline-tools

          # fetch latest commandline-tools (we'll call it "latest")
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          unzip -q cmdtools.zip
          rm cmdtools.zip
          mv cmdline-tools latest

          # set env vars for later steps
          echo "export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$HOME/.buildozer/android/platform/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Accept Android SDK licenses and install platforms/build-tools
        run: |
          source $GITHUB_ENV

          yes | sdkmanager --sdk_root="$ANDROID_HOME" --licenses > /dev/null || true

          sdkmanager --sdk_root="$ANDROID_HOME" \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"

          yes | sdkmanager --sdk_root="$ANDROID_HOME" --licenses

      - name: Build APK (debug)
        run: |
          source $GITHUB_ENV
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
