name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/.android-sdk
      ANDROID_HOME: ${{ github.workspace }}/.android-sdk
      PATH: ${{ github.workspace }}/.android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/.android-sdk/platform-tools:/usr/local/bin:/usr/bin:/bin
      # ép các biến Android cho p4a/buildozer
      ANDROIDAPI: "34"
      ANDROIDMINAPI: "21"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            wget \
            tar \
            openjdk-17-jdk \
            python3-setuptools \
            python3-venv \
            libffi-dev \
            libssl-dev \
            liblzma-dev \
            zlib1g-dev \
            libjpeg-dev \
            libfreetype6-dev \
            cmake \
            autoconf \
            automake \
            libtool \
            pkg-config

      - name: Install buildozer
        run: |
          pip install --upgrade pip
          # buildozer stable
          pip install buildozer Cython

      - name: Prepare Android SDK / sdkmanager
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT/cmdline-tools"

          # Tải commandline tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          unzip -q cmdtools.zip
          rm cmdtools.zip

          # Đổi tên đúng cấu trúc ("latest")
          mv cmdline-tools latest

          # sanity check
          test -f "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"

      - name: Accept Android SDK licenses and install platforms/build-tools
        run: |
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses || true

          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "platforms;android-${ANDROIDAPI}" \
            "build-tools;34.0.0"

          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses

      - name: Build APK (debug)
        run: |
          # Symlink SDK để buildozer nghĩ SDK nằm trong ~/.buildozer như bình thường
          mkdir -p $HOME/.buildozer/android/platform
          if [ ! -d $HOME/.buildozer/android/platform/android-sdk ]; then
            ln -s "$ANDROID_SDK_ROOT" $HOME/.buildozer/android/platform/android-sdk
          fi

          # Giả lập cấu trúc tools/bin cũ để tránh crash sdkmanager path legacy
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
          if [ -f "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
            ln -sf "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
              $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
          fi
          if [ -f "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager" ]; then
            ln -sf "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager" \
              $HOME/.buildozer/android/platform/android-sdk/tools/bin/avdmanager
          fi

          # Ensure license auto-accept in spec
          if ! grep -q "android.accept_sdk_license" buildozer.spec; then
            echo "android.accept_sdk_license = True" >> buildozer.spec
          fi

          # Đảm bảo buildozer.spec đã set android.archs = arm64-v8a
          # (ta chỉ build 64-bit để giảm rủi ro libffi fail trên armeabi-v7a)
          if ! grep -q "android.archs" buildozer.spec; then
            echo "android.archs = arm64-v8a" >> buildozer.spec
          fi

          # Đặt JAVA_HOME cho Gradle
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH

          # Cuối cùng build APK debug
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
