name: Build Android APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip libffi-dev libssl-dev \
            autoconf automake libtool pkg-config \
            python3-dev libncurses5 libncurses5-dev libtinfo5 \
            build-essential openjdk-17-jdk \
            libsqlite3-dev zlib1g zlib1g-dev \
            libbz2-dev libreadline-dev libgdbm-dev liblzma-dev \
            libblas-dev liblapack-dev

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: loginapp-apk
          path: bin/*.apk
